import com.example.droolspringboot.model.OrderRequest;
import com.example.droolspringboot.model.CustomerType;

global com.example.droolspringboot.model.OrderDiscount orderDiscount;

dialect "mvel"

rule "Age based discount"
    when
        OrderRequest(age < 20 || age > 50)
    then
        System.out.println("==========Adding 10% discount for Kids/ senior customer=============");
        orderDiscount.setDiscount(orderDiscount.getDiscount() + 10);
end
rule "Age based discount 1"
    when
        OrderRequest(age < 30 )
    then
        System.out.println("==========Adding 5% discount for Kids/ senior customer=============");
        orderDiscount.setDiscount(orderDiscount.getDiscount() + 5);
end